version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run: 
          name: "Install Requirements"
          shell: /bin/bash
          command: npm install
      - run:
          name: "Build Library"
          shell: /bin/bash
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run Tests and Collect Coverage"
          shell: /bin/bash
          command: npm test
      
workflows:
  version: 2
  main:
    jobs:
      - build
      - test:
          requires:
            - build